#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
pages_build_output_dir = "./build/client"
send_metrics = false

[[d1_databases]]
binding = "DB"
database_name = "prompt-storage-db"
database_id = "5b308b68-0293-4576-9f0d-3ad83007f60c"